# Generated by Django 5.1.7 on 2025-03-19 14:45

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gsm', models.CharField(max_length=3)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(default='ordered', max_length=16)),
                ('order_time', models.DateTimeField(default=datetime.datetime(2025, 3, 19, 14, 45, 11, 399293))),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(default='granted', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets')),
            ],
        ),
    ]
