# Generated by Django 5.1.7 on 2025-03-19 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 14, 53, 29, 442620)),
        ),
    ]
