# Generated by Django 5.1.7 on 2025-03-19 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_tickets_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 15, 19, 7, 377485)),
        ),
    ]
