# Generated by Django 5.1.3 on 2025-03-24 13:38

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_tickets_order_time'),
        ('users', '0005_alter_organisation_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedtickets',
            name='type',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 18, 38, 1, 784322)),
        ),
        migrations.CreateModel(
            name='UsedTickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('use_time', models.DateTimeField(default=datetime.datetime(2025, 3, 24, 18, 38, 1, 785321))),
                ('assigned_tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.assignedtickets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
