# Generated by Django 5.1.3 on 2025-03-27 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_assignedtickets_type_alter_tickets_order_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtickets',
            name='used_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='used_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tickets',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 13, 56, 27, 344766)),
        ),
        migrations.DeleteModel(
            name='UsedTickets',
        ),
    ]
