# Generated by Django 5.1.3 on 2025-03-27 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_assignedtickets_used_quantity_tickets_used_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtickets',
            name='used_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 14, 14, 40, 174104)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='used_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
