# Generated by Django 5.1.7 on 2025-04-04 13:42

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_assignedtickets_assign_time_alter_tickets_order_time'),
        ('users', '0005_alter_organisation_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtickets',
            name='assign_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 13, 42, 11, 653629)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 13, 42, 11, 653169)),
        ),
        migrations.CreateModel(
            name='UsingTicketsData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('used_time', models.DateTimeField(default=datetime.datetime(2025, 4, 4, 13, 42, 11, 653997))),
                ('quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
