# Generated by Django 5.1.7 on 2025-04-04 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_assignedtickets_assign_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usingticketsdata',
            name='gsm',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='assignedtickets',
            name='assign_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 13, 45, 49, 316220)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 13, 45, 49, 315644)),
        ),
        migrations.AlterField(
            model_name='usingticketsdata',
            name='used_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 13, 45, 49, 316707)),
        ),
    ]
