# Generated by Django 5.1.7 on 2025-04-09 14:49

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_usingticketsdata_gsm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedQRs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('qr_id', models.UUIDField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assignedtickets',
            name='assign_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 14, 49, 25, 198039)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 14, 49, 25, 197697)),
        ),
        migrations.AlterField(
            model_name='usingticketsdata',
            name='used_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 14, 49, 25, 198342)),
        ),
    ]
