# Generated by Django 5.1.7 on 2025-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='bin',
            field=models.IntegerField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
